[package]
name    = "omnireach-glue"
version.workspace = true
edition.workspace = true

[dependencies]
omnireach-core = { workspace = true }

tokio      = { workspace = true }
reqwest    = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }
chrono     = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
