[package]
name = "omnireach"
version.workspace = true
edition.workspace = true

[[bin]]
name = "omnireach"
path = "src/main.rs"

[package.metadata.rorpc]
client_path = "../../../frontend/src/rpc/bindings.ts"

[dependencies]
omnireach-core = { workspace = true }
omnireach-store = { workspace = true }
omnireach-glue = { workspace = true }
omnireach-server = { workspace = true }

tokio = { workspace = true }
axum = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }

rorpc = { workspace = true }
