[package]
name = "omnireach-server"
version.workspace = true
edition.workspace = true

[dependencies]
omnireach-core = { workspace = true }
omnireach-store = { workspace = true }
omnireach-glue = { workspace = true }

tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
tokio-stream = "0.1"
