// AUTO-GENERATED by rorpc — do not edit manually.
// Re-generate: rorpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

export const SessionStatusSchema = z.union([
  z.literal("connected"),
  z.literal("disconnected")
]);

export type SessionStatus = z.infer<typeof SessionStatusSchema>;

export const SessionSchema = z.object({
  id: z.uuid(),
  name: z.string().min(1).max(100),
  phone_number: z.string().min(1),
  status: SessionStatusSchema,
  hourly_limit: z.number().int().min(1).max(10000),
  daily_limit: z.number().int().min(1).max(100000),
  hourly_sent_timestamps: z.array(z.number().int()),
  daily_sent_timestamps: z.array(z.number().int()),
  last_activity_at: z.iso.datetime({ offset: true }).optional()
});

export type Session = z.infer<typeof SessionSchema>;

export const CreateSessionInputSchema = z.object({
  name: z.string().min(1).max(100),
  phone_number: z.string().min(1),
  api_key: z.string().min(1),
  hourly_limit: z.number().int().optional(),
  daily_limit: z.number().int().optional()
});

export type CreateSessionInput = z.infer<typeof CreateSessionInputSchema>;

export const contract = {
} as const;

export type Contract = typeof contract;