// AUTO-GENERATED by rorpc — do not edit manually.
// Re-generate: rorpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

// ============================================================================
// SSE Event Types
// ============================================================================

export const ProcessedItemSchema = z.object({
  item_id: z.uuid(),
  new_status: z.string(),
  sent_at: z.number().int().nullable(),
  error: z.string().nullable(),
  response_payload: z.string().nullable()
});

export type ProcessedItem = z.infer<typeof ProcessedItemSchema>;


// ============================================================================
// Input Types - Omnireach Core Types Session
// ============================================================================

export const CreateSessionInputSchema = z.object({
  name: z.string().min(1).max(100),
  phone_number: z.string().min(1),
  api_key: z.string().min(1),
  hourly_limit: z.number().int().nullable(),
  daily_limit: z.number().int().nullable()
});

export type CreateSessionInput = z.infer<typeof CreateSessionInputSchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Template
// ============================================================================

export const TemplateSchema = z.object({
  id: z.uuid(),
  title: z.string().min(1).max(200),
  title_ar: z.string().nullable(),
  category: z.string().min(1).max(100),
  category_ar: z.string().nullable(),
  text: z.string().min(1),
  text_ar: z.string().nullable(),
  image_url: z.string().nullable(),
  image_file_name: z.string().nullable(),
  suggested_variables: z.array(z.string()),
  created_at: z.iso.datetime({ offset: true }),
  updated_at: z.iso.datetime({ offset: true })
});

export type Template = z.infer<typeof TemplateSchema>;


// ============================================================================
// Enum Types
// ============================================================================

export const LogLevelSchema = z.union([
  z.literal("info"),
  z.literal("warn"),
  z.literal("error"),
  z.literal("success")
]);

export type LogLevel = z.infer<typeof LogLevelSchema>;

export const LogCategorySchema = z.union([
  z.literal("verification"),
  z.literal("send"),
  z.literal("rate_limit"),
  z.literal("scheduler"),
  z.literal("session"),
  z.literal("system")
]);

export type LogCategory = z.infer<typeof LogCategorySchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Log Entry
// ============================================================================

export const LogEntrySchema = z.object({
  id: z.uuid(),
  timestamp: z.iso.datetime({ offset: true }),
  level: LogLevelSchema,
  category: LogCategorySchema,
  message: z.string().min(1),
  details: z.record(z.string(), z.unknown()).nullable()
});

export type LogEntry = z.infer<typeof LogEntrySchema>;


// ============================================================================
// Enum Types
// ============================================================================

export const CampaignStatusSchema = z.union([
  z.literal("draft"),
  z.literal("scheduled"),
  z.literal("running"),
  z.literal("paused"),
  z.literal("completed"),
  z.literal("cancelled")
]);

export type CampaignStatus = z.infer<typeof CampaignStatusSchema>;

export const ContactVerificationStatusSchema = z.union([
  z.literal("unverified"),
  z.literal("checking"),
  z.literal("registered"),
  z.literal("unregistered"),
  z.literal("error")
]);

export type ContactVerificationStatus = z.infer<typeof ContactVerificationStatusSchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Contact
// ============================================================================

export const ContactSchema = z.object({
  id: z.uuid(),
  campaign_id: z.uuid(),
  name: z.string().min(1).max(200),
  raw_phone: z.string(),
  formatted_phone: z.string(),
  normalized_phone: z.string().min(1),
  custom_fields: z.record(z.string(), z.string()),
  verification_status: ContactVerificationStatusSchema,
  verification_error: z.string().nullable(),
  verified_at: z.iso.datetime({ offset: true }).nullable(),
  wa_id: z.string().nullable()
});

export type Contact = z.infer<typeof ContactSchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Campaign
// ============================================================================

export const CampaignSchema = z.object({
  id: z.uuid(),
  title: z.string().min(1).max(200),
  template_text: z.string().min(1),
  image_url: z.string().nullable(),
  image_file_name: z.string().nullable(),
  media_ref: z.string().nullable(),
  session_ids: z.array(z.uuid()),
  status: CampaignStatusSchema,
  created_at: z.iso.datetime({ offset: true }),
  started_at: z.iso.datetime({ offset: true }).nullable(),
  completed_at: z.iso.datetime({ offset: true }).nullable(),
  scheduled_for: z.iso.datetime({ offset: true }).nullable(),
  total_contacts: z.number().int(),
  verified_contacts: z.number().int(),
  unregistered_count: z.number().int(),
  sent_count: z.number().int(),
  skipped_count: z.number().int(),
  failed_count: z.number().int(),
  is_archived: z.boolean(),
  archived_at: z.iso.datetime({ offset: true }).nullable(),
  contacts: z.array(ContactSchema)
});

export type Campaign = z.infer<typeof CampaignSchema>;


// ============================================================================
// Input Types - Omnireach Core Types Contact
// ============================================================================

export const CreateContactInputSchema = z.object({
  name: z.string().min(1).max(200),
  raw_phone: z.string(),
  formatted_phone: z.string(),
  normalized_phone: z.string().min(1),
  custom_fields: z.record(z.string(), z.string()),
  verification_status: ContactVerificationStatusSchema.nullable(),
  wa_id: z.string().nullable()
});

export type CreateContactInput = z.infer<typeof CreateContactInputSchema>;


// ============================================================================
// Domain Types - Omnireach Server Handlers Media
// ============================================================================

export const UploadResponseSchema = z.object({
  media_ref: z.string(),
  expires_at: z.string(),
  url: z.string()
});

export type UploadResponse = z.infer<typeof UploadResponseSchema>;


// ============================================================================
// Domain Types - Omnireach Store Queue
// ============================================================================

export const QueueStatsSchema = z.object({
  pending: z.number().int(),
  sending: z.number().int(),
  sent: z.number().int(),
  failed: z.number().int(),
  held: z.number().int()
});

export type QueueStats = z.infer<typeof QueueStatsSchema>;


// ============================================================================
// Enum Types
// ============================================================================

export const SessionStatusSchema = z.union([
  z.literal("connected"),
  z.literal("disconnected")
]);

export type SessionStatus = z.infer<typeof SessionStatusSchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Session
// ============================================================================

export const SessionSchema = z.object({
  id: z.uuid(),
  name: z.string().min(1).max(100),
  phone_number: z.string().min(1),
  status: SessionStatusSchema,
  hourly_limit: z.number().int().min(1).max(10000),
  daily_limit: z.number().int().min(1).max(100000),
  hourly_sent_timestamps: z.array(z.number().int()),
  daily_sent_timestamps: z.array(z.number().int()),
  last_activity_at: z.iso.datetime({ offset: true }).nullable()
});

export type Session = z.infer<typeof SessionSchema>;


// ============================================================================
// Request Types
// ============================================================================

export const SendTestRequestSchema = z.object({
  phone: z.string(),
  message: z.string()
});

export type SendTestRequest = z.infer<typeof SendTestRequestSchema>;


// ============================================================================
// Input Types - Omnireach Server Handlers Queue
// ============================================================================

export const ListQueueQuerySchema = z.object({
  campaign_id: z.uuid().nullable()
});

export type ListQueueQuery = z.infer<typeof ListQueueQuerySchema>;


// ============================================================================
// Input Types - Omnireach Core Types Template
// ============================================================================

export const CreateTemplateInputSchema = z.object({
  title: z.string().min(1).max(200),
  title_ar: z.string().nullable(),
  category: z.string().min(1).max(100),
  category_ar: z.string().nullable(),
  text: z.string().min(1),
  text_ar: z.string().nullable(),
  image_url: z.string().nullable(),
  image_file_name: z.string().nullable(),
  suggested_variables: z.array(z.string())
});

export type CreateTemplateInput = z.infer<typeof CreateTemplateInputSchema>;


// ============================================================================
// Request Types
// ============================================================================

export const VerifyBatchRequestSchema = z.object({
  session_id: z.string(),
  phones: z.array(z.string())
});

export type VerifyBatchRequest = z.infer<typeof VerifyBatchRequestSchema>;


// ============================================================================
// Input Types - Omnireach Core Types Settings
// ============================================================================

export const UpdateSettingsInputSchema = z.object({
  scheduler_start_hour: z.number().int().nullable(),
  scheduler_end_hour: z.number().int().nullable(),
  scheduler_strict_time_window: z.boolean().nullable(),
  wabridge_base_url: z.string().nullable(),
  wabridge_timeout_ms: z.number().int().nullable()
});

export type UpdateSettingsInput = z.infer<typeof UpdateSettingsInputSchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Settings
// ============================================================================

export const AppSettingsSchema = z.object({
  scheduler_start_hour: z.number().int().min(0).max(23),
  scheduler_end_hour: z.number().int().min(0).max(23),
  scheduler_strict_time_window: z.boolean(),
  wabridge_base_url: z.string().min(1),
  wabridge_timeout_ms: z.number().int().min(100).max(60000)
});

export type AppSettings = z.infer<typeof AppSettingsSchema>;


// ============================================================================
// Input Types - Omnireach Core Types Campaign
// ============================================================================

export const CreateCampaignInputSchema = z.object({
  title: z.string().min(1).max(200),
  template_text: z.string().min(1),
  image_url: z.string().nullable(),
  media_ref: z.string().nullable(),
  session_ids: z.array(z.uuid()),
  contacts: z.array(CreateContactInputSchema),
  status: CampaignStatusSchema.nullable()
});

export type CreateCampaignInput = z.infer<typeof CreateCampaignInputSchema>;


// ============================================================================
// Domain Types - Omnireach Server Handlers Scheduler
// ============================================================================

export const TickResponseSchema = z.object({
  processed: z.array(ProcessedItemSchema),
  new_logs: z.array(LogEntrySchema)
});

export type TickResponse = z.infer<typeof TickResponseSchema>;


// ============================================================================
// Enum Types
// ============================================================================

export const QueueItemStatusSchema = z.union([
  z.literal("pending"),
  z.literal("verifying"),
  z.literal("sending"),
  z.literal("sent"),
  z.literal("skipped_unregistered"),
  z.literal("failed"),
  z.literal("held_rate_limit"),
  z.literal("held_time_window"),
  z.literal("cancelled")
]);

export type QueueItemStatus = z.infer<typeof QueueItemStatusSchema>;


// ============================================================================
// Domain Types - Omnireach Core Types Queue Item
// ============================================================================

export const QueueItemSchema = z.object({
  id: z.uuid(),
  campaign_id: z.uuid(),
  campaign_title: z.string().min(1).max(200),
  contact_id: z.uuid(),
  phone: z.string().min(1),
  recipient_name: z.string().nullable(),
  rendered_text: z.string(),
  image_url: z.string().nullable(),
  media_ref: z.string().nullable(),
  status: QueueItemStatusSchema,
  assigned_session_id: z.uuid().nullable(),
  attempts: z.number().int(),
  last_error: z.string().nullable(),
  sent_at: z.iso.datetime({ offset: true }).nullable(),
  scheduled_for: z.iso.datetime({ offset: true }).nullable(),
  rate_limit_hold_until: z.iso.datetime({ offset: true }).nullable(),
  time_window_hold_until: z.iso.datetime({ offset: true }).nullable(),
  response_payload: z.string().nullable()
});

export type QueueItem = z.infer<typeof QueueItemSchema>;


// ============================================================================
// Input Types - Omnireach Core Types Template
// ============================================================================

export const UpdateTemplateInputSchema = z.object({
  title: z.string().nullable(),
  title_ar: z.string().nullable(),
  category: z.string().nullable(),
  category_ar: z.string().nullable(),
  text: z.string().nullable(),
  text_ar: z.string().nullable(),
  image_url: z.string().nullable(),
  image_file_name: z.string().nullable(),
  suggested_variables: z.array(z.string()).nullable()
});

export type UpdateTemplateInput = z.infer<typeof UpdateTemplateInputSchema>;


// ============================================================================
// Request Types
// ============================================================================

export const TickRequestSchema = z.object({
  item_ids: z.array(z.uuid())
});

export type TickRequest = z.infer<typeof TickRequestSchema>;


// ============================================================================
// Enum Types
// ============================================================================

export const SseEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("campaign_created"), data: z.object({ campaign_id: z.string(), title: z.string() }) }),
  z.object({ type: z.literal("campaign_status"), data: z.object({ campaign_id: z.string(), status: z.string() }) }),
  z.object({ type: z.literal("queue_item_updated"), data: z.object({ item_id: z.string(), new_status: z.string(), campaign_id: z.string() }) }),
  z.object({ type: z.literal("queue_item_added"), data: z.object({ item_id: z.string(), campaign_id: z.string(), phone: z.string() }) }),
  z.object({ type: z.literal("queue_stats"), data: z.object({ pending: z.number().int(), sending: z.number().int(), sent: z.number().int(), failed: z.number().int(), held: z.number().int() }) }),
  z.object({ type: z.literal("session_status"), data: z.object({ session_id: z.string(), status: z.string(), qr_code_data: z.string().nullable() }) }),
  z.object({ type: z.literal("log_entry"), data: z.record(z.string(), z.unknown()) }),
  z.object({ type: z.literal("contact_verify_progress"), data: z.object({ job_id: z.string(), checked: z.number().int(), total: z.number().int(), registered: z.number().int(), unregistered: z.number().int() }) }),
  z.object({ type: z.literal("contact_verify_complete"), data: z.object({ job_id: z.string(), results: z.record(z.string(), z.unknown()) }) })
]);

export type SseEvent = z.infer<typeof SseEventSchema>;


// ============================================================================
// Domain Types - Omnireach Server Handlers Contacts
// ============================================================================

export const VerifyBatchResponseSchema = z.object({
  job_id: z.string()
});

export type VerifyBatchResponse = z.infer<typeof VerifyBatchResponseSchema>;


// ============================================================================
// Input Types - Omnireach Core Types Session
// ============================================================================

export const UpdateSessionInputSchema = z.object({
  name: z.string().nullable(),
  api_key: z.string().nullable(),
  hourly_limit: z.number().int().nullable(),
  daily_limit: z.number().int().nullable()
});

export type UpdateSessionInput = z.infer<typeof UpdateSessionInputSchema>;

// ============================================================================
// Error Schemas
// ============================================================================

const StandardApiErrors = {
  NOT_FOUND: {
    data: z.string()
  },
  BAD_REQUEST: {
    data: z.string()
  },
  CONFLICT: {
    data: z.string()
  },
  UNAUTHORIZED: {},
  STORE: {
    data: z.unknown()
  },
  GLUE: {
    data: z.unknown()
  },
  INTERNAL: {
    data: z.string()
  },
} as const;

// ============================================================================
// API Contract
// ============================================================================

export const contract = {
  campaigns: {
    retryFailed: oc
      .meta(openapi({ method: "POST", path: "/api/campaigns/{id}/retry-failed" }))
      .input(z.object({ id: z.uuid() }))
      .output(z.record(z.string(), z.unknown()))
      .errors(StandardApiErrors),
    unarchive: oc
      .meta(openapi({ method: "POST", path: "/api/campaigns/{id}/unarchive" }))
      .input(z.object({ id: z.uuid() }))
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    archive: oc
      .meta(openapi({ method: "POST", path: "/api/campaigns/{id}/archive" }))
      .input(z.object({ id: z.uuid() }))
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    resume: oc
      .meta(openapi({ method: "POST", path: "/api/campaigns/{id}/resume" }))
      .input(z.object({ id: z.uuid() }))
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    pause: oc
      .meta(openapi({ method: "POST", path: "/api/campaigns/{id}/pause" }))
      .input(z.object({ id: z.uuid() }))
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    destroy: oc
      .meta(openapi({ method: "DELETE", path: "/api/campaigns/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(z.void())
      .errors(StandardApiErrors),
    update: oc
      .meta(openapi({ method: "PATCH", path: "/api/campaigns/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    create: oc
      .meta(openapi({ method: "POST", path: "/api/campaigns" }))
      .input(CreateCampaignInputSchema)
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    getById: oc
      .meta(openapi({ method: "GET", path: "/api/campaigns/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(CampaignSchema)
      .errors(StandardApiErrors),
    list: oc
      .meta(openapi({ method: "GET", path: "/api/campaigns" }))
      .input(z.void())
      .output(z.array(CampaignSchema))
      .errors(StandardApiErrors),
  },
  contacts: {
    verifyBatch: oc
      .meta(openapi({ method: "POST", path: "/api/contacts/verify-batch" }))
      .input(VerifyBatchRequestSchema)
      .output(VerifyBatchResponseSchema)
      .errors(StandardApiErrors),
  },
  events: {
    events: oc
      .meta(openapi({ method: "GET", path: "/api/events" }))
      .input(z.void())
      .output(asyncIteratorObject(SseEventSchema)),
  },
  logs: {
    clear: oc
      .meta(openapi({ method: "DELETE", path: "/api/logs" }))
      .input(z.void())
      .output(z.void())
      .errors(StandardApiErrors),
    list: oc
      .meta(openapi({ method: "GET", path: "/api/logs" }))
      .input(z.void())
      .output(z.array(LogEntrySchema))
      .errors(StandardApiErrors),
  },
  queue: {
    retry: oc
      .meta(openapi({ method: "POST", path: "/api/queue/{id}/retry" }))
      .input(z.object({ id: z.uuid() }))
      .output(QueueItemSchema)
      .errors(StandardApiErrors),
    cancel: oc
      .meta(openapi({ method: "POST", path: "/api/queue/{id}/cancel" }))
      .input(z.object({ id: z.uuid() }))
      .output(QueueItemSchema)
      .errors(StandardApiErrors),
    stats: oc
      .meta(openapi({ method: "GET", path: "/api/queue/stats" }))
      .input(z.void())
      .output(QueueStatsSchema)
      .errors(StandardApiErrors),
    list: oc
      .meta(openapi({ method: "GET", path: "/api/queue" }))
      .input(ListQueueQuerySchema)
      .output(z.array(QueueItemSchema))
      .errors(StandardApiErrors),
  },
  scheduler: {
    tick: oc
      .meta(openapi({ method: "POST", path: "/api/scheduler/tick" }))
      .input(TickRequestSchema)
      .output(TickResponseSchema)
      .errors(StandardApiErrors),
  },
  sessions: {
    sendTest: oc
      .meta(openapi({ method: "POST", path: "/api/sessions/{id}/send-test" }))
      .input(z.object({ id: z.uuid() }).extend(SendTestRequestSchema.shape))
      .output(z.void())
      .errors(StandardApiErrors),
    resetLimits: oc
      .meta(openapi({ method: "POST", path: "/api/sessions/{id}/reset-limits" }))
      .input(z.object({ id: z.uuid() }))
      .output(SessionSchema)
      .errors(StandardApiErrors),
    sync: oc
      .meta(openapi({ method: "POST", path: "/api/sessions/{id}/sync" }))
      .input(z.object({ id: z.uuid() }))
      .output(SessionSchema)
      .errors(StandardApiErrors),
    destroy: oc
      .meta(openapi({ method: "DELETE", path: "/api/sessions/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(z.void())
      .errors(StandardApiErrors),
    update: oc
      .meta(openapi({ method: "PATCH", path: "/api/sessions/{id}" }))
      .input(z.object({ id: z.uuid() }).extend(UpdateSessionInputSchema.shape))
      .output(SessionSchema)
      .errors(StandardApiErrors),
    create: oc
      .meta(openapi({ method: "POST", path: "/api/sessions" }))
      .input(CreateSessionInputSchema)
      .output(SessionSchema)
      .errors(StandardApiErrors),
    getById: oc
      .meta(openapi({ method: "GET", path: "/api/sessions/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(SessionSchema)
      .errors(StandardApiErrors),
    list: oc
      .meta(openapi({ method: "GET", path: "/api/sessions" }))
      .input(z.void())
      .output(z.array(SessionSchema))
      .errors(StandardApiErrors),
  },
  settings: {
    update: oc
      .meta(openapi({ method: "PATCH", path: "/api/settings" }))
      .input(UpdateSettingsInputSchema)
      .output(AppSettingsSchema)
      .errors(StandardApiErrors),
    load: oc
      .meta(openapi({ method: "GET", path: "/api/settings" }))
      .input(z.void())
      .output(AppSettingsSchema)
      .errors(StandardApiErrors),
  },
  templates: {
    destroy: oc
      .meta(openapi({ method: "DELETE", path: "/api/templates/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(z.void())
      .errors(StandardApiErrors),
    update: oc
      .meta(openapi({ method: "PATCH", path: "/api/templates/{id}" }))
      .input(z.object({ id: z.uuid() }).extend(UpdateTemplateInputSchema.shape))
      .output(TemplateSchema)
      .errors(StandardApiErrors),
    create: oc
      .meta(openapi({ method: "POST", path: "/api/templates" }))
      .input(CreateTemplateInputSchema)
      .output(TemplateSchema)
      .errors(StandardApiErrors),
    getById: oc
      .meta(openapi({ method: "GET", path: "/api/templates/{id}" }))
      .input(z.object({ id: z.uuid() }))
      .output(TemplateSchema)
      .errors(StandardApiErrors),
    list: oc
      .meta(openapi({ method: "GET", path: "/api/templates" }))
      .input(z.void())
      .output(z.array(TemplateSchema))
      .errors(StandardApiErrors),
  },
} as const;

export type Contract = typeof contract;